=== Muhammed-Ahmed-Ismail/xml-labs/project/XML_files/contacts_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="contacts">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="employee"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="employee">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="phone" type="xs:string"/>
        <xs:element name="address" type="xs:string"/>
        <xs:element name="email" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Muhammed-Ahmed-Ismail/xml-labs/project/XML_files/contacts-xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<contacts xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="contacts_schema.xsd">


    <employee>
        <name>mukammed</name>
        <phone>5434</phone>
        <address>717 Ibn Easel St Azzaheria</address>
        <email>Muhammed@gmail.com</email>
    </employee>
    <employee>
        <name>Ali</name>
        <phone>5434</phone>
        <address>717 Ibn Easel St Azzaheria</address>
        <email>Muhammed@gmail.com</email>
    </employee>
</contacts>
