=== Muhammed-Ahmed-Ismail/xml-labs/day_2/contacts.dtd
<!ELEMENT contacts (employee+)>
<!ELEMENT employee (name, phones, adresses, email)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT phones (phone+)>
<!ELEMENT phone (#PCDATA)>
<!ATTLIST phone
          type CDATA #REQUIRED>
<!ELEMENT adresses (address)>
<!ELEMENT address (country, city, region, street, building)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT building (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== Muhammed-Ahmed-Ismail/xml-labs/day_2/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contacts SYSTEM "contacts.dtd">
<?xml-stylesheet type="text/css" href="contacts.css"?>

<contacts>
                      
                      <employee>
                      <name > Muhammed Ahmed Ismail</name>
                        <phones>
                          <phone  type="mobile">0123456789</phone> 
                          <phone type="home">0123456789</phone>
                          <phone type="work">0123456789</phone>
                        </phones>
                        <adresses>
                            <address >
                                          <country> Egypt</country>
                                          <city> Alexandria</city>
                                          <region>Bacus</region>
                                          <street> st1</street>
                                          <building> 7</building>
                            </address>
                        </adresses>
                        <email> muhammed@gmail,com</email>
                        
                      
                      </employee> 
                      

                      
</contacts>
